notifications:
  email: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

script: phpunit --bootstrap vendor/autoload.php tests

before_script:
  - "composer install --dev --prefer-source --no-interaction"